apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac/promtail-serviceaccount.yaml
  - rbac/promtail-clusterrole.yaml
  - rbac/promtail-clusterrolebinding.yaml
  - configmaps/grafana-configmap.yaml
  - configmaps/promtail-configmap.yaml
  - deployments/loki-deployment.yaml
  - deployments/grafana-deployment.yaml
  - services/loki-service.yaml
  - services/grafana-service.yaml
  - daemonsets/promtail-daemonset.yaml