apiVersion: v1
kind: Service
metadata:
  name: jupyter-notebook
  namespace: kubeflow
spec:
  ports:
  - name: http
    port: 8888
    nodePort: 31400
  selector:
    app: jupyter-notebook
  type: ClusterIP