apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: kubeflow
data:
  config: |
    instanceID: kubeflow-pipelines
    artifactRepository:
      s3:
        bucket: mlpipeline
        endpoint: minio-service:9000
        insecure: true
        accessKeySecret:
          name: minio-secret
          key: accesskey
        secretKeySecret:
          name: minio-secret
          key: secretkey