apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: kubeflow
data:
  config: |
    instanceID: kubeflow-pipelines
    artifactRepository:
      s3:
        bucket: mlpipeline
        endpoint: minio-service:9000
        insecure: true
        accessKey: minio
        secretKey: minio123