apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: kubeflow
data:
  init.sql: |
    CREATE USER IF NOT EXISTS 'mlpipeline'@'%' IDENTIFIED WITH mysql_native_password BY '';
    GRANT ALL PRIVILEGES ON mlpipeline.* TO 'mlpipeline'@'%';
    FLUSH PRIVILEGES;