apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argo-crds.yaml
- crds/workflows-crd.yaml
- crds/scheduledworkflow-crd.yaml
- configmaps/workflow-controller-configmap.yaml
- deployments/workflow-controller-deployment.yaml
- deployments/ml-pipeline-deploy.yaml
- services/ml-pipeline-service.yaml
- deployments/ml-pipeline-ui-deployment.yaml
- services/ml-pipeline-ui-service.yaml
- deployments/ml-pipeline-visualizationserver-deployment.yaml
- services/ml-pipeline-visualizationserver-service.yaml
- deployments/metadata-envoy-deployment.yaml
- services/metadata-envoy-service.yaml
- deployments/metadata-grpc-deployment.yaml
- services/metadata-grpc-service.yaml
- deployments/ml-pipeline-persistenceagent-deployment.yaml
- deployments/ml-pipeline-scheduledworkflow-deployment.yaml