apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-envoy
  namespace: kubeflow
spec:
  selector:
    matchLabels:
      app: metadata-envoy
  template:
    metadata:
      labels:
        app: metadata-envoy
    spec:
      containers:
      - name: container
        image: gcr.io/ml-pipeline/metadata-envoy:2.0.0
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: metadata-envoy-service
  namespace: kubeflow
spec:
  ports:
  - port: 9090
  selector:
    app: metadata-envoy