apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: kubeflow
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "true"
        - name: MYSQL_DATABASE
          value: mlpipeline
        - name: MYSQL_ROOT_PASSWORD
          value: ""
        - name: MYSQL_INIT_SCRIPT
          value: |
            CREATE USER IF NOT EXISTS 'mlpipeline'@'%' IDENTIFIED WITH mysql_native_password BY '';
            GRANT ALL PRIVILEGES ON mlpipeline.* TO 'mlpipeline'@'%';
            FLUSH PRIVILEGES;


        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        - name: mysql-init
          mountPath: /docker-entrypoint-initdb.d
          readOnly: true
        
      volumes:
      - name: mysql-storage
        hostPath:
          path: /opt/k8s_data/kf-cluster/mysql
          type: DirectoryOrCreate
      - name: mysql-init
        configMap:
          name: mysql-init-script