apiVersion: v1
kind: Pod
metadata:
  name: test-pod-2
  namespace: kubeflow
spec:
  containers:
  - name: notebook
    image: ubuntu:latest
    command: ["/bin/sh", "-c", "while true; do echo hello; sleep 10;done"]
    resources:
      requests:
        cpu: "1"
        memory: "2Gi"
      limits:
        cpu: "1"
        memory: "2Gi"
