apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-writer
  namespace: kubeflow
spec:
  selector:
    matchLabels:
      app: metadata-writer
  template:
    metadata:
      labels:
        app: metadata-writer
    spec:
      serviceAccountName: pipeline-runner
      initContainers:
      - name: wait-for-minio
        image: minio/mc:RELEASE.2024-01-16T16-06-34Z
        command:
        - sh
        - -c
        - |
          until mc alias set minio http://minio-service:9000 minio minio123 && mc ls minio/ > /dev/null 2>&1; do
            echo "Waiting for MinIO..."
            sleep 5
          done
      containers:
      - name: main
        image: gcr.io/ml-pipeline/metadata-writer:2.0.0
        env:
        - name: NAMESPACE_TO_WATCH
          value: kubeflow
        - name: METADATA_GRPC_SERVICE_HOST
          value: metadata-grpc-service
        - name: METADATA_GRPC_SERVICE_PORT
          value: "8080"