apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notebook-ingress
  namespace: kubeflow
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: notebook-service
            port:
              number: 8888