apiVersion: v1
kind: Pod
metadata:
  name: notebook-python-demo
  namespace: kubeflow
  labels:
    app: notebook
    name: python-demo
spec:
  containers:
  - name: notebook
    image: python:3.12-slim
    command: ["/bin/bash"]
    args: ["-c", "pip install jupyter && jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''"]
    ports:
    - containerPort: 8888
      name: notebook
    resources:
      requests:
        memory: "2Gi"
        cpu: "1"
      limits:
        memory: "2Gi"
        cpu: "1"
    volumeMounts:
    - name: notebook-data
      mountPath: /home/jovyan
  volumes:
  - name: notebook-data
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: notebook-python-demo
  namespace: kubeflow
spec:
  selector:
    name: python-demo
  ports:
  - port: 8888
    targetPort: 8888
    name: notebook