apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: python-demo
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
      - name: notebook
        image: quay.io/jupyter/scipy-notebook:latest
        command:
        - "jupyter"
        args:
        - "lab"
        - "--ip=0.0.0.0"
        - "--port=8888"
        - "--no-browser"
        - "--allow-root"
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "1"
            memory: "2Gi"
        volumeMounts:
        - name: workspace
          mountPath: /home/jovyan/work
      volumes:
      - name: workspace
        emptyDir: {}