apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: python-demo
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
      - name: notebook
        image: jupyter/scipy-notebook:latest
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "1"
            memory: "2Gi"
        volumeMounts:
        - name: workspace
          mountPath: /home/jovyan/work
      volumes:
      - name: workspace
        emptyDir: {}