apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/namespace.yaml
- base/rbac.yaml
- storage/minio-secret.yaml
- storage/deployments/minio-deploy.yaml
- storage/services/minio-service.yaml
- storage/deployments/mysql-deploy.yaml
- storage/services/mysql-service.yaml
- pipelines/argo-workflow.yaml
- pipelines/scheduledworkflow-crd.yaml
- pipelines/deployments/ml-pipeline-deploy.yaml
- pipelines/services/ml-pipeline-service.yaml
- pipelines/ml-pipeline-ui.yaml
- pipelines/ml-pipeline-visualizationserver.yaml
- pipelines/metadata-envoy.yaml
- pipelines/metadata-grpc.yaml
- pipelines/ml-pipeline-persistenceagent.yaml
- pipelines/ml-pipeline-scheduledworkflow.yaml
- notebooks/jupyter.yaml