apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/namespace.yaml
- base/rbac.yaml
- storage/minio.yaml
- storage/mysql.yaml
- pipelines/argo-workflow.yaml
- pipelines/scheduledworkflow-crd.yaml
- pipelines/ml-pipeline.yaml
- pipelines/ml-pipeline-ui.yaml
- pipelines/ml-pipeline-visualizationserver.yaml
- pipelines/ml-pipeline-persistenceagent.yaml
- pipelines/ml-pipeline-scheduledworkflow.yaml
- notebooks/jupyter.yaml