apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: kubeflow
spec:
  ports:
  - name: api
    port: 9000
  - name: console
    port: 9001
  selector:
    app: minio
---
apiVersion: v1
kind: Service
metadata:
  name: minio-console
  namespace: kubeflow
spec:
  ports:
  - name: console
    port: 9001
    nodePort: 31390
  selector:
    app: minio
  type: NodePort