apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: monitoring
data:
  config.yml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push

    scrape_configs:
      - job_name: kubeflow-pods
        static_configs:
          - targets:
              - localhost
            labels:
              job: kubeflow-pods
              namespace: kubeflow
              __path__: /var/log/pods/kubeflow_*/*/*.log
        pipeline_stages:
          - regex:
              expression: '/var/log/pods/kubeflow_(?P<app>[a-z-]+)-[a-z0-9]+-[a-z0-9]+_.*'
              source: filename
          - labels:
              app:
          - cri: {}