apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-notebook
  namespace: kubeflow
spec:
  selector:
    matchLabels:
      app: jupyter-notebook
  template:
    metadata:
      labels:
        app: jupyter-notebook
    spec:
      serviceAccountName: pipeline-runner
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ['sh', '-c', 'chown -R 1000:100 /home/jovyan && chmod -R 755 /home/jovyan']
        volumeMounts:
        - name: notebook-storage
          mountPath: /home/jovyan
      containers:
      - name: notebook
        image: jupyter/scipy-notebook:python-3.10
        env:
        - name: JUPYTER_ENABLE_LAB
          value: "yes"
        - name: JUPYTER_TOKEN
          value: ""
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: notebook-storage
          mountPath: /home/jovyan/
      volumes:
      - name: notebook-storage
        hostPath:
          path: /opt/k8s_data/kf-cluster/notebooks
          type: DirectoryOrCreate