apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-notebook
  namespace: kubeflow
spec:
  selector:
    matchLabels:
      app: jupyter-notebook
  template:
    metadata:
      labels:
        app: jupyter-notebook
    spec:
      serviceAccountName: pipeline-runner
      
      containers:
      - name: notebook
        image: jupyter/scipy-notebook:python-3.10
        env:
        - name: JUPYTER_ENABLE_LAB
          value: "yes"

        ports:
        - containerPort: 8888
        volumeMounts:
        - name: notebook-storage
          mountPath: /home/jovyan/
      volumes:
      - name: notebook-storage
        hostPath:
          path: /opt/k8s_data/kf-cluster/notebooks
          type: DirectoryOrCreate