apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebook-controller
  namespace: kubeflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notebook-controller
  template:
    metadata:
      labels:
        app: notebook-controller
    spec:
      serviceAccountName: notebook-controller
      containers:
      - name: manager
        image: kubeflownotebookswg/notebook-controller:v1.10.0-rc.1
        command:
        - /manager
        env:
        - name: USE_ISTIO
          value: "false"
        - name: ISTIO_GATEWAY
          value: "kubeflow/kubeflow-gateway"
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notebook-controller
  namespace: kubeflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: notebook-controller
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "events", "configmaps", "secrets"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
  verbs: ["*"]
- apiGroups: ["kubeflow.org"]
  resources: ["notebooks"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: notebook-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: notebook-controller
subjects:
- kind: ServiceAccount
  name: notebook-controller
  namespace: kubeflow