apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac/pipeline-runner-serviceaccount.yaml
  - rbac/pipeline-runner-clusterrole.yaml
  - rbac/pipeline-runner-clusterrolebinding.yaml